### ISSUE TITLE
undefined reference to `fsal::Location::Location...

### ISSUE THREAD

**Issue by ghost** [podgorskiy/fsal#2]
Hello. I am using your library in a program of mine, and I am encountering an error related to linking:
```
in function ep::fs_manager::manager::add_vec_paths(std::vector<std::filesystem::__cxx11::path, std::allocator<std::filesystem::__cxx11::path> >)':
.../fs_manager.hh:19: undefined reference to `fsal::Location::Location(std::filesystem::__cxx11::path const&, fsal::Location::Options, fsal::PathType, fsal::LinkType)'
/usr/bin/ld: .../fs_manager.hh:25: undefined reference to `fsal::Location::Location(std::filesystem::__cxx11::path const&, fsal::Location::Options, fsal::PathType, fsal::LinkType)'
```

(Path information has been omitted)

This is what my CMake project does in relation to linking fsal:
```
add_subdirectory(fsal)
include_directories(./ fsal/sources/)

add_dependencies(omitted fsal)
target_link_libraries(omitted PRIVATE fsal stdc++fs lz4)
```

Is there an error in the way I am including your library?

**Comment by podgorskiy** [comment]
Usage seems to be correct. The only thing that comes to my mind is a mismatch of C++ standard.
I here https://github.com/podgorskiy/fsal/blob/cf0f16a02123416176bb02a96bfe89ac8541dbb7/CMakeLists.txt#L7 it sets C++14, but if that does not match your project, ABI won't be compatible and it won't link.

Could you please put a bunch of #pragma message in here https://github.com/podgorskiy/fsal/blob/cf0f16a02123416176bb02a96bfe89ac8541dbb7/sources/fsal_common.h#L26 and here https://github.com/podgorskiy/fsal/blob/cf0f16a02123416176bb02a96bfe89ac8541dbb7/sources/fsal_common.h#L35  to see which one is used, <experimental/filesystem> or <filesystem>? If included header differs for fsal and your project, then that's the reason.

**Comment by brushtool** [comment]
Okay. I changed the standard to C++ 17, as if I were on clang++.
Now, I've encountered a new error, a segfault, when trying to open a VPK file.
```
__vsprintf_internal (string=0x7fffffffd140 "`\321\377\377\377\177", 
    maxlen=maxlen@entry=18446744073709551615, format=0x555555608940 "pak01_%s.vpk", 
    args=args@entry=0x7fffffffcf40, mode_flags=mode_flags@entry=0) at iovsprintf.c:85
85	iovsprintf.c: No such file or directory.
(gdb) 
91	in iovsprintf.c
(gdb) 
92	in iovsprintf.c
(gdb) 
96	in iovsprintf.c
(gdb) 
98	in iovsprintf.c
(gdb) 
99	in iovsprintf.c
(gdb) 
__sprintf (s=<optimized out>, format=<optimized out>) at sprintf.c:33
33	sprintf.c: No such file or directory.
(gdb) 
0x000055555557e8d4 in fsal::VPKReader::OpenArchive(fsal::FileSystem, fsal::Location, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
(gdb) 
Single stepping until exit from function _ZN4fsal9VPKReader11OpenArchiveENS_10FileSystemENS_8LocationERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE,
which has no line number information.

Program received signal SIGSEGV, Segmentation fault.
```
The VPK file directory and name is /media/games/SteamLibrary-Linux/steamapps/common/GarrysMod/sourceengine/hl2_misc_dir.vpk. I noticed that it was string printing pak01_%s.vpk. Might it be looking for a non existent VPK file? hl2_misc_dir.vpk's different parts are named hl2_misc_<number starting from 000>.vpk.

**Comment by podgorskiy** [comment]
I'll need to improve error reporting here.
Yes, looks like it tries to open nonexisting file.
The function is:

    Archive OpenVpkArchive(FileSystem fs, Location directory, const std::string& formatString = "pak01_%s.vpk")

It has the third argument, which tells the naming of the archives. It defaults to `pak01_%s.vpk`, but you will need to change that to `hl2_misc_%s.vpk`

And please note that the argument `directory` should be to the directory that contains vpk files.

Something like:

    auto archive = fsal::OpenVpkArchive(fs, "/media/games/SteamLibrary-Linux/steamapps/common/GarrysMod/sourceengine", "hl2_misc_%s.vpk");

**Comment by brushtool** [comment]
Thank you. I don't have any further issues, so I'll close this issue
